fix NoSuchMethodError in Otel SDK shutdown
Apparently, there's more than one okhttp3 on the classpath. We shade ours into
a private copy to eliminate the clash.

```
Exception in thread "okhttp-dispatch-1" java.lang.NoSuchMethodError: 'okhttp3.Headers okhttp3.Response.trailers()'
    at io.opentelemetry.exporter.sender.okhttp.internal.OkHttpGrpcSender.grpcStatus(OkHttpGrpcSender.java:169)
    at io.opentelemetry.exporter.sender.okhttp.internal.OkHttpGrpcSender.access$000(OkHttpGrpcSender.java:64)
    at io.opentelemetry.exporter.sender.okhttp.internal.OkHttpGrpcSender$1.onResponse(OkHttpGrpcSender.java:149)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
```